#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
xs_env_dir="$(cd "${repo_dir}/.." && pwd)"
emu="${xs_env_dir}/XiangShan/build/emu"
ref_so="${xs_env_dir}/XiangShan/ready-to-run/riscv64-nemu-interpreter-so"
image="${repo_dir}/stage1/vector-add/build/cie2026-stage1-vector-add-riscv64-xs.bin"
wave_dir="${repo_dir}/stage1/waveform"
wave_file="${wave_dir}/vector-add-vadd.vcd"
full_log="${repo_dir}/stage1/logs/vector-add-wave-run.full.log"
summary_log="${repo_dir}/stage1/logs/vector-add-wave-run.log"
begin_cycle="${WAVE_BEGIN:-2850}"
end_cycle="${WAVE_END:-3300}"

for required_file in "${emu}" "${ref_so}" "${image}"; do
  if [[ ! -f "${required_file}" ]]; then
    echo "missing required file: ${required_file}" >&2
    exit 1
  fi
done

mkdir -p "${wave_dir}"

if "${emu}" \
    --diff="${ref_so}" \
    -i "${image}" \
    --dump-wave \
    --wave-path="${wave_file}" \
    -b "${begin_cycle}" \
    -e "${end_cycle}" >"${full_log}" 2>&1; then
  emu_status=0
else
  emu_status=$?
fi

{
  echo "[wave] range: ${begin_cycle}-${end_cycle}"
  echo "[wave] file: ${wave_file}"
  echo "[wave] bytes: $(stat -c '%s' "${wave_file}")"
  echo "[wave] sha256: $(sha256sum "${wave_file}" | cut -d' ' -f1)"
  echo "[wave] key output:"
  grep -aE "vector-add PASS|HIT GOOD TRAP|HIT BAD TRAP|instrCnt|Guest cycle spent|Host time spent" "${full_log}" \
    | sed -E $'s/\r$//; s/[[:space:]]+$//; s/\x1b\\[[0-9;]*[[:alpha:]]//g'
  echo "[wave] exit status: ${emu_status}"
} | tee "${summary_log}"

grep -aFq "vector-add PASS" "${full_log}"
grep -aFq "HIT GOOD TRAP" "${full_log}"
grep -aFq '$version Generated by VerilatedVcd $end' "${wave_file}"
exit "${emu_status}"
